# This file was generated by GoReleaser. DO NOT EDIT.
cask "atct" do
  version "0.30.0"

  on_macos do
    on_intel do
      sha256 "1d3a4bd572a85ba8f7a3a648ea42a57bc256932e4ac8fd773bc182e8e8778656"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
    on_arm do
      sha256 "423b5fd11bae380a5a6907a9e3804d57503dc5f523465ce0ff1fe4012d7fc175"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
  end

  on_linux do
    on_intel do
      sha256 "2991743a0a31def0a7525b83fed71b21bd0c1d8633863262fb04645da80430a8"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_linux_amd64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
    on_arm do
      sha256 "ca6d5571ed9c904674ee982bfc067c3f6abff3466e8290042377803bde7c86d9"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_linux_arm64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
  end

  name "atct"
  desc "The air traffic control tower for your coding agents"
  homepage "https://github.com/michiomochi/atct"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atct"
  binary "atct-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atct"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atct-mcp"]
    end
  end

  # No zap stanza required

end
