# This file was generated by GoReleaser. DO NOT EDIT.
cask "atct" do
  version "0.20.0"

  on_macos do
    on_intel do
      sha256 "125484c294e6b4835f0111d8af99fcf004a2834325b249d45f146f1f374b9479"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
    on_arm do
      sha256 "e2202074de54713e708b52813592aad8a2deaab10b02771f1048057ac6ae1cd4"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b395fc3c84b5efbd5c6ee2cdc6363c0bd7cdf8e1d03dd5e4948718a6786188a"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_linux_amd64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
    on_arm do
      sha256 "da591c6d7aa6c08ead654ac2914959be0ec49afd43b924d4a421caaa470ba3ca"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_linux_arm64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
  end

  name "atct"
  desc "The air traffic control tower for your coding agents"
  homepage "https://github.com/michiomochi/atct"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atct"
  binary "atct-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atct"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atct-mcp"]
    end
  end

  # No zap stanza required

end
