# This file was generated by GoReleaser. DO NOT EDIT.
cask "atct" do
  version "0.39.0"

  on_macos do
    on_intel do
      sha256 "caf13815ef77b3535527b600c11f83445ddbbaf3bf65c10b9fc6748026ad7693"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
    on_arm do
      sha256 "4729353f346299cd74a980f90e7bc38606371d04a2d123be858791fe2afdddfe"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
  end

  on_linux do
    on_intel do
      sha256 "712668a6abdebffc93ef5904df2abfec80eaa657dc62059286d379ae9f4f947a"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_linux_amd64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
    on_arm do
      sha256 "cd5170bc99d4c66642d818606de89577e68eaebd5429e8b3c5d6a727bff6abbc"
      url "https://github.com/michiomochi/atct/releases/download/v#{version}/atct_#{version}_linux_arm64.tar.gz",
        verified: "github.com/michiomochi/atct"
    end
  end

  name "atct"
  desc "The air traffic control tower for your coding agents"
  homepage "https://github.com/michiomochi/atct"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atct"
  binary "atct-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atct"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atct-mcp"]
    end
  end

  # No zap stanza required

end
